Config = {}
--[[ Main section ]]--
Config.menuPosition = 'right'
Config.textDistance = 1.0
Config.notifDuration = 10000
Config.oxTarget = true
Config.log = 'https://discord.com/api/webhooks/1172686703006318662/W1x8YLEEHwJFLwnx0NOTpZV6L4dvexICpBwLkxjKfPwzYu-oMYnT6Rv9RNPbTtEK5eTf' --  'YOUR_WEBHOOK'
Config.currencySymbol= "$"

Config.CanBuyJob = true    -- Peux tu achete pour l entreprise   

Config.vehicleColors = {    -- Allow custom RGB Colors for primary and secondary? Currently without any money take
    CanChoose = true,
    primary = true,
    secondary = true
}
Config.defaultgaragecar = 'legion'
Config.defaultgarageboat = 'pier'
Config.defaultgarageaicraft = 'lsia'


--[[ Vehicle shops configuration ]]--
Config.vehicleShops = {
    --[[
        shopLabel = This is label of the shop
        shopCoords = Shop point coords (also for blip)
        previewCoords = Where will the vehicle spawn? Vec4!
        vehicleSpawnCoords = When you buy the vehicle, where should it spawn? Vec4! (If not empty, it will be added to the garage)
        vehicleList = String 'car, boats, airplane' to be compatible with your garages
        blipData = Example: {color = 5, sprite = 755, scale = 0.8},
        npcData = Example: {model = joaat('A_M_M_HasJew_01'), position = vec4(-331.8239, -2792.7698, 4.0002, 90.6536)},
        license = String 'dmv', 'boat' whatever you have for your license system (look in db)  
    --]]
    {
        shopLabel = 'Deluxe Motorsport',
        shopIcon = 'fa-solid fa-car',
        shopCoords = vec3(-46.15347, -1097.91, 26.42234), 
        previewCoords = vec4(-41.85375, -1097.913, 26.42234, 71.72385), 
        vehicleSpawnCoords = vec4(-12.09255, -1087.388, 26.67617, 162.4797),
        vehicleList = 'vehicles',
        blipData = {color = 5, sprite = 810, scale = 0.8},
        npcData = {model = joaat('IG_Avon'), position = vec4(-33.05927, -1101.873, 25.42236, 70.30009)},
        showcaseVehicle = {
            {vehicleModel = joaat('bifta'), coords = vec4(-45.1562, -1116.163, 25.87129, 2.637821), color = {247, 159, 123}},
            {vehicleModel = joaat('t20'), coords = vec4(-47.98648, -1116.417, 26.0102, 2.168004), color = {40, 42, 54}},
            {vehicleModel = joaat('rhinehart'), coords = vec4(-50.7855, -1116.398, 26.17439, 2.566503), color = {255, 0, 32}},   --ok
            {vehicleModel = joaat('ztype'), coords = vec4(-53.46579, -1116.217, 25.85851, 5.358676), color = {33, 33, 33}},
        }
    },
    {
        shopLabel = 'Port de LS',
        shopIcon = 'fa-solid fa-anchor',
        shopCoords = vec3(-332.1013, -2792.5610, 4.0002), 
        previewCoords = vec4(-338.1895, -2801.4814, 7.5375, 0.4449), 
        vehicleSpawnCoords = vec4(-338.1895, -2801.4814, 7.5375, 0.4449),
        vehicleList = 'boats',
        blipData = {color = 5, sprite = 755, scale = 0.8},
        npcData = {model = joaat('A_M_M_HasJew_01'), position = vec4(-332.1013, -2792.5610, 4.0002, 98.5272)},
    },
    {
        shopLabel = 'LS Travel',
        shopIcon = 'fa-solid fa-plane',
        shopCoords = vec3(1746.7318, 3296.3875, 41.1424), 
        previewCoords = vec4(1728.4298, 3313.7102, 41.2235, 195.8193), 
        vehicleSpawnCoords = vec4(1770.8486, 3238.9597, 42.1628, 32.3031),
        vehicleList = 'planes',
        blipData = {color = 5, sprite = 90, scale = 0.8},
        npcData = {model = joaat('A_M_M_HasJew_01'), position = vec4(1746.7318, 3296.3875, 40.1424, 166.0)},
    },
}

Config.vehicleList = {
    ['vehicles'] = {
        {label = 'compacts', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Asbo', vehicleModel = joaat('asbo'), vehiclePrice = 8000},
            {label = 'Blista', vehicleModel = joaat('blista'), vehiclePrice = 6500 },
            {label = 'Brioso R/A', vehicleModel = joaat('brioso'), vehiclePrice = 24500},
            {label = 'Brioso 300', vehicleModel = joaat('brioso2'), vehiclePrice = 18000},
            {label = 'Brioso 300 Widebody', vehicleModel = joaat('brioso3'), vehiclePrice = 10000},
            {label = 'Champion', vehicleModel = joaat('champion'), vehiclePrice = 350000},
            {label = 'Club', vehicleModel = joaat('club'), vehiclePrice = 4000}, 
            {label = 'Dilettante', vehicleModel = joaat('dilettante'), vehiclePrice = 12000},
            {label = 'Issi', vehicleModel = joaat('issi2'), vehiclePrice = 10000},
            {label = 'Issi Classic', vehicleModel = joaat('issi2'), vehiclePrice = 3000},
            --{label = 'IssiB', vehicleModel = joaat('issi4'), vehiclePrice = 3600},
            --{label = 'IssiC', vehicleModel = joaat('issi5'), vehiclePrice = 4200},
            {label = 'Kanjo Blista', vehicleModel = joaat('kanjo'), vehiclePrice = 5000},
            {label = 'Panto', vehicleModel = joaat('panto'), vehiclePrice = 6000},
            {label = 'Prairie', vehicleModel = joaat('prairie'), vehiclePrice = 9000},
            {label = 'Rhapsody', vehicleModel = joaat('rhapsody'), vehiclePrice = 7000},
            {label = 'Weevil', vehicleModel = joaat('weevil'), vehiclePrice = 4000},
        }},
        {label = 'coupes', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Cognoscenti Cabrio', vehicleModel = joaat('cogcabrio'), vehiclePrice = 92000},
            {label = 'Exemplar', vehicleModel = joaat('exemplar'), vehiclePrice = 32000},
            {label = 'F620', vehicleModel = joaat('f620'), vehiclePrice = 40000},
            {label = 'Felon', vehicleModel = joaat('felon'), vehiclePrice = 45000}, 
            {label = 'Felon GT', vehicleModel = joaat('felon2'), vehiclePrice = 55000}, 
            {label = 'Hermes', vehicleModel = joaat('hermes'), vehiclePrice = 50000},
            {label = 'Jackal', vehicleModel = joaat('jackal'), vehiclePrice = 38000},
            {label = 'Kanjo SJ', vehicleModel = joaat('kanjosj'), vehiclePrice = 5500},
            {label = 'Oracle XS', vehicleModel = joaat('oracle'), vehiclePrice = 40000},
            {label = 'Oracle XS 2', vehicleModel = joaat('oracle2'), vehiclePrice = 35000},
            {label = 'Postlude', vehicleModel = joaat('postlude'), vehiclePrice = 7500},
            {label = 'Previon', vehicleModel = joaat('Previon'), vehiclePrice = 25000},
            {label = 'Sentinel', vehicleModel = joaat('sentinel'), vehiclePrice = 32000},
            {label = 'Sentinel XS', vehicleModel = joaat('sentinel2'), vehiclePrice = 40000},
            {label = 'Windsor', vehicleModel = joaat('windsor'), vehiclePrice = 300000}, 
            {label = 'Windsor Drop', vehicleModel = joaat('windsor2'), vehiclePrice = 320000},
            {label = 'Zion', vehicleModel = joaat('zion'), vehiclePrice = 28000},
            {label = 'Zion Cabrio', vehicleModel = joaat('zion2'), vehiclePrice = 30000},
        }},
        {label = 'motorcycles', defaultIndex = 2, dbData = 'car', values = { 
            {label = 'Akuma', vehicleModel = joaat('AKUMA'), vehiclePrice = 11500},
            {label = 'Avarus', vehicleModel = joaat('avarus'), vehiclePrice = 27500},
            {label = 'Bagger', vehicleModel = joaat('bagger'), vehiclePrice = 24500},
            {label = 'Bati 801', vehicleModel = joaat('bati'), vehiclePrice = 13500},
            {label = 'Bati 801RR', vehicleModel = joaat('bati2'), vehiclePrice = 15000},
            {label = 'BF400', vehicleModel = joaat('bf400'), vehiclePrice = 18500},
            {label= 'Carbon RS', vehicleModel = joaat('carbonrs'), vehiclePrice= 20000},    
            {label= 'Chimera', vehicleModel = joaat('chimera'), vehiclePrice= 30000},
            {label= 'Cliffhanger', vehicleModel = joaat('cliffhanger'), vehiclePrice= 25000},
            {label= 'Daemon', vehicleModel = joaat('daemon'), vehiclePrice= 15000},
            {label= 'Daemon High', vehicleModel = joaat('daemon2'), vehiclePrice= 13500},
            {label= 'Defiler', vehicleModel = joaat('defiler'), vehiclePrice= 10000},
            {label= 'Diabolus', vehicleModel = joaat('diablous'), vehiclePrice= 15000},
            {label= 'Diabolus Custom', vehicleModel = joaat('diablous2'), vehiclePrice= 20000},
            {label= 'Double T', vehicleModel = joaat('double'), vehiclePrice= 28000},
            {label= 'Enduro', vehicleModel = joaat('enduro'), vehiclePrice= 5500},
            {label= 'Esskey', vehicleModel = joaat('esskey'), vehiclePrice= 4200},
            {label= 'Faggio', vehicleModel = joaat('faggio'), vehiclePrice= 1500},
            {label= 'Vespa', vehicleModel = joaat('faggio2'), vehiclePrice= 2500},
            {label= 'Faggio Mod', vehicleModel = joaat('faggio3'), vehiclePrice= 2300},
            {label= 'FCR 1000', vehicleModel = joaat('fcr'), vehiclePrice= 15000},
            {label= 'FCR 1000 Custom', vehicleModel = joaat('fcr2'), vehiclePrice= 20000},
            {label= 'Gargoyle', vehicleModel = joaat('gargoyle'), vehiclePrice= 16500},
            {label= 'Hakuchou', vehicleModel = joaat('hakuchou'), vehiclePrice= 31000},
            {label= 'Hakuchou Sport', vehicleModel = joaat('hakuchou2'), vehiclePrice= 80000},
            {label= 'Hexer', vehicleModel = joaat('hexer'), vehiclePrice= 12000},
            {label= 'Innovation', vehicleModel = joaat('innovation'), vehiclePrice= 23500},
            {label= 'Lectro', vehicleModel = joaat('lectro'), vehiclePrice= 18700},
            {label= 'Manchez', vehicleModel = joaat('manchez'), vehiclePrice= 7300},
            {label= 'Manchez 2', vehicleModel = joaat('manchez2'), vehiclePrice= 15000},
            {label= 'Manchez Scout C', vehicleModel = joaat('manchez3'), vehiclePrice= 15000},
            {label= 'Nemesis', vehicleModel = joaat('nemesis'), vehiclePrice= 5800},
            {label= 'Nightblade', vehicleModel = joaat('nightblade'), vehiclePrice= 35000},
            {label= 'PCJ-600', vehicleModel = joaat('pcj'), vehiclePrice= 5000},
            {label= 'Powersurge', vehicleModel = joaat('powersurge'), vehiclePrice= 34000},
            {label= 'Rat Bike', vehicleModel = joaat('ratbike'), vehiclePrice= 20000},
            {label= 'Reever', vehicleModel = joaat('reever'), vehiclePrice= 60000},
            {label= 'Rampant Tricycle', vehicleModel = joaat('rrocket'), vehiclePrice= 19000},    
            {label= 'Ruffian', vehicleModel = joaat('ruffian'), vehiclePrice= 9000},    
            {label= 'Sanchez', vehicleModel = joaat('sanchez'), vehiclePrice= 5300},    
            {label= 'Sanchez Sport', vehicleModel = joaat('sanchez2'), vehiclePrice= 5300},    
            {label= 'Sanctus', vehicleModel = joaat('sanctus'), vehiclePrice= 25000},    
            {label= 'Shinobi', vehicleModel = joaat('shinobi'), vehiclePrice= 45000},    
            {label= 'Sovereign', vehicleModel = joaat('sovereign'), vehiclePrice= 20000},    
            {label= 'Stryder', vehicleModel = joaat('stryder'), vehiclePrice= 35000},    
            {label= 'Thrust', vehicleModel = joaat('thrust'), vehiclePrice= 19500},
            {label= 'Vader', vehicleModel = joaat('vader'), vehiclePrice= 7200},
            {label= 'Vindcator', vehicleModel = joaat('vindicator'), vehiclePrice= 35000},
            {label= 'Vortex', vehicleModel = joaat('vortex'), vehiclePrice= 9800},
            {label= 'Woflsbane', vehicleModel = joaat('wolfsbane'), vehiclePrice= 12000},
            {label= 'Zombie', vehicleModel = joaat('zombiea'), vehiclePrice= 9500},
            {label= 'Zombie Chopper', vehicleModel = joaat('zombieb'), vehiclePrice= 12000},


        }},
        {label = 'cycles', defaultIndex = 2, dbData = 'car', values = {
            {label= 'BMX (velo)', vehicleModel = joaat('bmx'), vehiclePrice= 200},
            {label= 'Caddy', vehicleModel = joaat('caddy'), vehiclePrice= 3000},
            {label= 'Caddy 2', vehicleModel = joaat('caddy2'), vehiclePrice= 3000},
            {label= 'Caddy 3', vehicleModel = joaat('caddy3'), vehiclePrice= 3000},
            {label= 'Cruiser (velo)', vehicleModel = joaat('cruiser'), vehiclePrice= 510},
            {label= 'Fixter (velo)', vehicleModel = joaat('fixter'), vehiclePrice= 225},
            {label= 'Scorcher (velo)', vehicleModel = joaat('scorcher'), vehiclePrice= 280},
            {label= 'Race bike Whippet', vehicleModel = joaat('tribike'), vehiclePrice= 500},
            {label= 'Race bike Endurex', vehicleModel = joaat('tribike2'), vehiclePrice= 500},
            {label= 'Tri bike (velo)', vehicleModel = joaat('tribike3'), vehiclePrice= 520},
        }},
        {label = 'muscles', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Blade', vehicleModel = joaat('blade'), vehiclePrice = 5000},
            {label = 'Broadway', vehicleModel = joaat('broadway'), vehiclePrice = 10000},
            {label = 'Buccaneer', vehicleModel = joaat('buccaneer'), vehiclePrice = 22500}, 
            {label = 'Buccaneer Rider', vehicleModel = joaat('buccaneer2'), vehiclePrice = 23000}, 
            {label = 'Buffalo STX', vehicleModel = joaat('buffalo4'), vehiclePrice = 50000},
            {label = 'Chino', vehicleModel = joaat('chino'), vehiclePrice = 15000},
            {label = 'Chino Luxe', vehicleModel = joaat('chino2'), vehiclePrice = 25000},
            {label = 'Clique', vehicleModel = joaat('clique'), vehiclePrice = 20000},
            {label = 'Coquette BlackFin', vehicleModel = joaat('coquette3'), vehiclePrice = 130000},
            {label = 'Deviant', vehicleModel = joaat('deviant'), vehiclePrice = 45000},
            {label = 'Dominator', vehicleModel = joaat('dominator'), vehiclePrice = 30000},
            {label = 'Dominator Pisswasser', vehicleModel = joaat('dominator2'), vehiclePrice = 20000},
            {label = 'Dominator GTX', vehicleModel = joaat('dominator3'), vehiclePrice = 55000},
            {label = 'Dominator 7', vehicleModel = joaat('dominator7'), vehiclePrice = 35000},
            {label = 'Dominator 8', vehicleModel = joaat('dominator8'), vehiclePrice = 50000},
            {label = 'Dukes', vehicleModel = joaat('dukes'), vehiclePrice = 15000},
            {label = 'Dukes Beater', vehicleModel = joaat('dukes3'), vehiclePrice = 15000},
            {label= 'Willard Eudora', vehicleModel = joaat('eudora'), vehiclePrice= 7500},
            {label= 'Faction', vehicleModel = joaat('faction'), vehiclePrice= 20000},
            {label= 'Faction Rider', vehicleModel = joaat('faction2'), vehiclePrice= 27000},
            {label= 'Faction XL', vehicleModel = joaat('faction3'), vehiclePrice= 28000},
            {label= 'Gauntlet', vehicleModel = joaat('gauntlet'), vehiclePrice= 30000},
            {label= 'Gauntlet Redwood', vehicleModel = joaat('gauntlet2'), vehiclePrice= 20000},
            {label= 'Gauntlet Classic', vehicleModel = joaat('gauntlet3'), vehiclePrice= 40000},
            {label= 'Gauntlet Hellfire', vehicleModel = joaat('gauntlet4'), vehiclePrice= 60000},
            {label= 'Gauntlet Classic Custom', vehicleModel = joaat('gauntlet5'), vehiclePrice= 35000},
            {label= 'Greenwood', vehicleModel = joaat('greenwood'), vehiclePrice= 15000},
            {label= 'Hotknife', vehicleModel = joaat('hotknife'), vehiclePrice= 60000},
            {label= 'Hustler', vehicleModel = joaat('hustler'), vehiclePrice= 62500},
            {label= 'Impaler', vehicleModel = joaat('impaler'), vehiclePrice= 15000},
            {label= 'Manana Custom', vehicleModel = joaat('manana2'), vehiclePrice= 15000},
            {label= 'Nightshade', vehicleModel = joaat('nightshade'), vehiclePrice= 40000},
            {label= 'Peyote Gasser', vehicleModel = joaat('peyote2'), vehiclePrice= 30000},
            {label= 'Phoenix', vehicleModel = joaat('phoenix'), vehiclePrice= 32000},
            {label= 'Picador', vehicleModel = joaat('picador'), vehiclePrice= 23000},
            {label= 'Rat-Truck', vehicleModel = joaat('ratloader2'), vehiclePrice= 15000},
            {label= 'Ruiner', vehicleModel = joaat('ruiner'), vehiclePrice= 9000},    
            {label= 'Imponte Ruiner ZZ-8', vehicleModel = joaat('ruiner4'), vehiclePrice= 9300},    
            {label= 'Sabre Turbo', vehicleModel = joaat('sabregt'), vehiclePrice= 25000},    
            {label= 'Sabre GT', vehicleModel = joaat('sabregt2'), vehiclePrice= 30000},   
            {label= 'Slamvan', vehicleModel = joaat('slamvan'), vehiclePrice= 18000},    
            {label= 'Slamvan Lost', vehicleModel = joaat('slamvan2'), vehiclePrice= 15000},    
            {label= 'Slamvan Custom', vehicleModel = joaat('slamvan3'), vehiclePrice= 23000},  
            {label= 'Stallion', vehicleModel = joaat('stalion'), vehiclePrice= 15000},    
            {label= 'Stallion Burger Shot', vehicleModel = joaat('stalion2'), vehiclePrice= 20000},   
            {label= 'Tahoma Coupe', vehicleModel = joaat('tahoma'), vehiclePrice= 23000},
            {label= 'Tampa', vehicleModel = joaat('tampa'), vehiclePrice= 25000},
            {label= 'Tulip', vehicleModel = joaat('tulip'), vehiclePrice= 13000},
            {label= 'Tulip M-100', vehicleModel = joaat('tulip2'), vehiclePrice= 15000},
            {label= 'Vamos', vehicleModel = joaat('vamos'), vehiclePrice= 20000},
            {label= 'Vigero', vehicleModel = joaat('vigero'), vehiclePrice= 12500},
            {label= 'Vigero 2', vehicleModel = joaat('vigero2'), vehiclePrice= 13000},
            {label= 'Virgo', vehicleModel = joaat('virgo'), vehiclePrice= 14000},
            {label= 'Virgo Classic Custom', vehicleModel = joaat('virgo2'), vehiclePrice= 25000},
            {label= 'Virgo Classic', vehicleModel = joaat('virgo3'), vehiclePrice= 30000},
            {label= 'Voodoo Custom', vehicleModel = joaat('voodoo'), vehiclePrice= 7200},
            {label= 'Voodoo', vehicleModel = joaat('voodoo2'), vehiclePrice= 3000},
            {label= 'Weevil Custom', vehicleModel = joaat('weevil2'), vehiclePrice= 15000},
            {label= 'Yosemite', vehicleModel = joaat('yosemite'), vehiclePrice= 33000},
            {label= 'Yosemite Drift', vehicleModel = joaat('yosemite2'), vehiclePrice= 60000},




        }},
        {label = 'offroads', defaultIndex = 2, dbData = 'car', values = {
            {label= 'Bf Injection', vehicleModel = joaat('bfinjection'), vehiclePrice= 10000},
            {label= 'Bifta', vehicleModel = joaat('bifta'), vehiclePrice= 8000},
            {label= 'Blazer', vehicleModel = joaat('blazer'), vehiclePrice= 10500},
            {label= 'Blazer Hot Rod', vehicleModel = joaat('blazer3'), vehiclePrice= 9500},
            {label= 'Street Blaze', vehicleModel = joaat('blazer4'), vehiclePrice= 5500},
            {label= 'Bodhi', vehicleModel = joaat('bodhi2'), vehiclePrice= 20000},
            {label= 'Karin Boor', vehicleModel = joaat('boor'), vehiclePrice= 11500},
            {label= 'Brawler', vehicleModel = joaat('brawler'), vehiclePrice= 50000},
            {label= 'Caracara 4x4', vehicleModel = joaat('caracara2'), vehiclePrice= 50000},
            {label= 'Duneloader', vehicleModel = joaat('dloader'), vehiclePrice= 10000},
            {label= 'Draugur', vehicleModel = joaat('draugur'), vehiclePrice= 60000},
            {label= 'Bubsta 6x6', vehicleModel = joaat('dubsta3'), vehiclePrice= 230000},
            {label= 'Dune Buggy', vehicleModel = joaat('dune'), vehiclePrice= 4000},
            {label= 'Everon', vehicleModel = joaat('everon'), vehiclePrice= 50000},
            {label= 'Freecrawler', vehicleModel = joaat('freecrawler'), vehiclePrice= 45000},
            {label= 'Guardian', vehicleModel = joaat('guardian'), vehiclePrice= 90000},
            {label= 'Hellion', vehicleModel = joaat('hellion'), vehiclePrice= 40000},
            {label= 'Kalahari', vehicleModel = joaat('kalahari'), vehiclePrice= 10000},
            {label= 'Kamacho', vehicleModel = joaat('kamacho'), vehiclePrice= 155000},
            {label= 'Outlaw', vehicleModel = joaat('outlaw'), vehiclePrice= 15000},
            {label= 'Rancher XL', vehicleModel = joaat('rancherxl'), vehiclePrice= 25000},
            {label= 'Rusty Rebel', vehicleModel = joaat('rebel'), vehiclePrice= 4000},
            {label= 'Rebel', vehicleModel = joaat('rebel2'), vehiclePrice= 8000},
            {label= 'Rusty Rebel', vehicleModel = joaat('rebel'), vehiclePrice= 4000},
            {label= 'Rebel', vehicleModel = joaat('rebel2'), vehiclePrice= 8000},
            {label= 'riata', vehicleModel = joaat('riata'), vehiclePrice= 40000},   
            {label= 'Sadler', vehicleModel = joaat('sadler'), vehiclePrice= 42000},    
            {label= 'Sandking', vehicleModel = joaat('sandking'), vehiclePrice= 45000},    
            {label= 'Sandking SWB', vehicleModel = joaat('sandking2'), vehiclePrice= 50000},  
            {label= 'Trophy Truck', vehicleModel = joaat('trophytruck'), vehiclePrice= 60000},
            {label= 'Trophy Truck Limited', vehicleModel = joaat('trophytruck2'), vehiclePrice= 60000},
            {label= 'Vagrant', vehicleModel = joaat('vagrant'), vehiclePrice= 30000},
            {label= 'Verus', vehicleModel = joaat('verus'), vehiclePrice= 15000},
            {label= 'Vetir', vehicleModel = joaat('vetir'), vehiclePrice= 75000},
            {label= 'Winky', vehicleModel = joaat('winky'), vehiclePrice= 25000},
            {label= 'Yosemite Rancher', vehicleModel = joaat('yosemite3'), vehiclePrice= 34000},




            
        }},
        {label = 'suvs', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Astron', vehicleModel = joaat('astron'), vehiclePrice = 54000},
            {label = 'Baller', vehicleModel = joaat('baller'), vehiclePrice = 22500},
            {label = 'Baller', vehicleModel = joaat('baller2'), vehiclePrice = 45000},
            {label = 'Baller Sport', vehicleModel = joaat('baller3'), vehiclePrice = 47500},
            {label = 'Baller LE LWB', vehicleModel = joaat('baller4'), vehiclePrice = 47500},
            {label = 'Baller ST', vehicleModel = joaat('baller7'), vehiclePrice = 50000},
            {label= 'BeeJay XL', vehicleModel = joaat('bjxl'), vehiclePrice= 20000},
            {label= 'Cavalcade', vehicleModel = joaat('cavalcade'), vehiclePrice= 100000},
            {label= 'Cavalcade', vehicleModel = joaat('cavalcade2'), vehiclePrice= 100000},
            {label= 'Contender', vehicleModel = joaat('contender'), vehiclePrice= 70000},
            {label= 'Dubsta', vehicleModel = joaat('dubsta'), vehiclePrice= 45000},
            {label= 'Dubsta Luxuary', vehicleModel = joaat('dubsta2'), vehiclePrice= 60000},
            {label= 'Fhantom', vehicleModel = joaat('fq2'), vehiclePrice= 17000},
            {label= 'Grabger', vehicleModel = joaat('granger'), vehiclePrice= 50000},
            {label= 'Gresley', vehicleModel = joaat('gresley'), vehiclePrice= 47500},
            {label= 'Habanero', vehicleModel = joaat('habanero'), vehiclePrice= 22500},
            {label= 'Huntley S', vehicleModel = joaat('huntley'), vehiclePrice= 40000},
            {label= 'Issi Rally', vehicleModel = joaat('issi8'), vehiclePrice= 145000},
            {label= 'I-Wagen', vehicleModel = joaat('iwagen'), vehiclePrice= 180000},
            {label= 'Jubilee', vehicleModel = joaat('jubilee'), vehiclePrice= 90000},
            {label= 'Landstalker', vehicleModel = joaat('landstalker'), vehiclePrice= 35000},
            {label= 'Landstalker XL', vehicleModel = joaat('landstalker2'), vehiclePrice= 25000},
            {label= 'Mesa', vehicleModel = joaat('mesa'), vehiclePrice= 16000},
            {label= 'Mesa Trail', vehicleModel = joaat('mesa3'), vehiclePrice= 40000},
            {label= 'Novak', vehicleModel = joaat('novak'), vehiclePrice= 25000},
            {label= 'Patriot', vehicleModel = joaat('patriot'), vehiclePrice= 55000},
            {label= 'Patriot 2', vehicleModel = joaat('patriot3'), vehiclePrice= 150000},
            {label= 'Radius', vehicleModel = joaat('radi'), vehiclePrice= 29000},
            {label= 'Rebla GTS', vehicleModel = joaat('rebla'), vehiclePrice= 25000},
            {label= 'Rocoto', vehicleModel = joaat('rocoto'), vehiclePrice= 45000}, 
            {label= 'Seminole', vehicleModel = joaat('seminole'), vehiclePrice= 25000},    
            {label= 'Seminole Frontier', vehicleModel = joaat('seminole2'), vehiclePrice= 22500},
            {label= 'Serrano', vehicleModel = joaat('serrano'), vehiclePrice= 22500},  
            {label= 'Squaddie', vehicleModel = joaat('squaddie'), vehiclePrice= 40000},  
            {label= 'Toros', vehicleModel = joaat('toros'), vehiclePrice= 25000},
            {label= 'XLS', vehicleModel = joaat('xls'), vehiclePrice= 32000},
        }},
        {label = 'sedans', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Asea', vehicleModel = joaat('asea'), vehiclePrice = 5000},
            {label = 'Asterope', vehicleModel = joaat('asterope'), vehiclePrice = 8000},
            {label= 'Cinquemila', vehicleModel = joaat('cinquemila'), vehiclePrice= 150000},
            {label= 'Cognoscenti 55', vehicleModel = joaat('cog55'), vehiclePrice= 80000},
            {label= 'Cognoscenti', vehicleModel = joaat('cognoscenti'), vehiclePrice= 70000},
            {label= 'Deity', vehicleModel = joaat('deity'), vehiclePrice= 450000},
            {label= 'Emperor', vehicleModel = joaat('emperor'), vehiclePrice= 12500},
            {label= 'Emperor 2', vehicleModel = joaat('emperor2'), vehiclePrice= 3500},
            {label= 'Fugitive', vehicleModel = joaat('fugitive'), vehiclePrice= 30000},
            {label= 'Glendale', vehicleModel = joaat('glendale'), vehiclePrice= 6500},
            {label= 'Glendale Custom', vehicleModel = joaat('glendale2'), vehiclePrice= 10000},
            {label= 'Ingot', vehicleModel = joaat('ingot'), vehiclePrice= 10000},
            {label= 'Intruder', vehicleModel = joaat('intruder'), vehiclePrice= 12500},
            {label= 'Premier', vehicleModel = joaat('premier'), vehiclePrice= 8000},
            {label= 'Primo', vehicleModel = joaat('primo'), vehiclePrice= 17000},
            {label= 'Primo Custom', vehicleModel = joaat('primo2'), vehiclePrice= 12000},
            {label= 'Regina', vehicleModel = joaat('regina'), vehiclePrice= 5000},
            {label= 'Rhinehart', vehicleModel = joaat('rhinehart'), vehiclePrice= 40000},    
            {label= 'Schafter', vehicleModel = joaat('schafter2'), vehiclePrice= 40000},    
            {label= 'Stafford', vehicleModel = joaat('stafford'), vehiclePrice= 50000},    
            {label= 'Stanier', vehicleModel = joaat('stanier'), vehiclePrice= 12500},    
            {label= 'Stratum', vehicleModel = joaat('stratum'), vehiclePrice= 12500},    
            {label= 'Super Diamond', vehicleModel = joaat('superd'), vehiclePrice= 420000},    
            {label= 'Surge', vehicleModel = joaat('surge'), vehiclePrice= 18000},  
            {label= 'Tailgater', vehicleModel = joaat('tailgater'), vehiclePrice= 17000},
            {label= 'Tailgater S', vehicleModel = joaat('tailgater2'), vehiclePrice= 34000},
            {label= 'Warrener', vehicleModel = joaat('warrener'), vehiclePrice= 6000},
            {label= 'Warrener HKR', vehicleModel = joaat('warrener2'), vehiclePrice= 20000},
            {label= 'Washington', vehicleModel = joaat('washington'), vehiclePrice= 15000},
        }},
        {label = 'sports', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Alpha', vehicleModel = joaat('alpha'), vehiclePrice = 50000},
            {label = 'Banshee', vehicleModel = joaat('banshee'), vehiclePrice = 90000},
            {label = 'Bestia GTS', vehicleModel = joaat('bestiagts'), vehiclePrice = 365000},
            {label = 'Blista Compact', vehicleModel = joaat('blista2'), vehiclePrice = 5500},
            {label = 'Blista Go Go Monkey', vehicleModel = joaat('blista3'), vehiclePrice = 5500},
            {label= 'Buffalo', vehicleModel = joaat('buffalo'), vehiclePrice= 35000},
            {label= 'Buffalo S', vehicleModel = joaat('buffalo2'), vehiclePrice= 35500},
            {label= 'Buffalo Sprunk', vehicleModel = joaat('buffalo3'), vehiclePrice= 35000},
            {label= 'Calico', vehicleModel = joaat('calico'), vehiclePrice= 7500},
            {label= 'Carbonizzare', vehicleModel = joaat('carbonizzare'), vehiclePrice= 80000},
            {label= 'Comet', vehicleModel = joaat('comet2'), vehiclePrice= 65000},
            {label= 'Comet Retro Custom', vehicleModel = joaat('comet3'), vehiclePrice= 52500},
            {label= 'Comet Safari', vehicleModel = joaat('comet4'), vehiclePrice= 50000},
            {label= 'Comet 5', vehicleModel = joaat('comet5'), vehiclePrice= 114500},
            {label= 'Comet 6', vehicleModel = joaat('comet6'), vehiclePrice= 110000},
            {label= 'Comet S2 Cabrio', vehicleModel = joaat('comet7'), vehiclePrice= 300000},
            {label= 'Coquette', vehicleModel = joaat('coquette'), vehiclePrice= 65000},
            {label= 'Coquette D10', vehicleModel = joaat('coquette4'), vehiclePrice= 100000},
            {label= 'Lampadati Corsita', vehicleModel = joaat('corsita'), vehiclePrice= 235000},
            {label= 'Cypher', vehicleModel = joaat('cypher'), vehiclePrice= 65000},
            {label= '8F Drafter', vehicleModel = joaat('drafter'), vehiclePrice= 50000},
            {label= 'Elegy Retro Custom', vehicleModel = joaat('elegy'), vehiclePrice= 50000},
            {label= 'Elegy', vehicleModel = joaat('elegy2'), vehiclePrice= 38500},
            {label= 'Euros', vehicleModel = joaat('euros'), vehiclePrice= 33500},
            {label= 'Everon Hotring', vehicleModel = joaat('everon2'), vehiclePrice= 51000},
            {label= 'Feltzer', vehicleModel = joaat('feltzer2'), vehiclePrice= 55000},
            {label= 'Stirling GT', vehicleModel = joaat('feltzer3'), vehiclePrice= 800000},
            {label= 'Flash GT', vehicleModel = joaat('flashgt'), vehiclePrice= 50000},
            {label= 'Furore GT', vehicleModel = joaat('furoregt'), vehiclePrice= 45000},
            {label= 'Fusilade', vehicleModel = joaat('fusilade'), vehiclePrice= 40000},
            {label= 'Futo', vehicleModel = joaat('futo'), vehiclePrice= 25000},
            {label= 'Futo GTX', vehicleModel = joaat('Futo2'), vehiclePrice= 30000},
            {label= 'GB200', vehicleModel = joaat('gb200'), vehiclePrice= 37500},
            {label= 'Growler', vehicleModel = joaat('growler'), vehiclePrice= 200000},
            {label= 'Hotring Sabre', vehicleModel = joaat('hotring'), vehiclePrice= 50000},
            {label= 'Imorgon', vehicleModel = joaat('imorgon'), vehiclePrice= 75000},
            {label= 'Issi Sport', vehicleModel = joaat('issi7'), vehiclePrice= 37500},
            {label= 'Itali GTO', vehicleModel = joaat('italigto'), vehiclePrice= 400000},
            {label= 'Itali RSX', vehicleModel = joaat('italirsx'), vehiclePrice= 1000000},
            {label= 'Jester', vehicleModel = joaat('jester'), vehiclePrice= 65000},
            {label= 'Jester(Racecar)', vehicleModel = joaat('jester2'), vehiclePrice= 135000},
            {label= 'Jester Classic', vehicleModel = joaat('jester3'), vehiclePrice= 37500},
            {label= 'Jester 4', vehicleModel = joaat('jester4'), vehiclePrice= 60000},
            {label= 'Jugular', vehicleModel = joaat('jugular'), vehiclePrice= 50000},
            {label= 'Khamelion', vehicleModel = joaat('khamelion'), vehiclePrice= 38000},
            {label= 'Komoda', vehicleModel = joaat('komoda'), vehiclePrice= 50000},
            {label= 'Kuruma', vehicleModel = joaat('kuruma'), vehiclePrice= 40000},
            {label= 'Locust', vehicleModel = joaat('locust'), vehiclePrice= 75000},
            {label= 'Lynx', vehicleModel = joaat('lynx'), vehiclePrice= 40000},
            {label= 'Mamba', vehicleModel = joaat('mamba'), vehiclePrice= 70000},
            {label= 'Massacro', vehicleModel = joaat('massacro'), vehiclePrice= 65000},
            {label= 'Massacro(Racecar)', vehicleModel = joaat('massacro2'), vehiclePrice= 130000},
            {label= 'Neo', vehicleModel = joaat('neo'), vehiclePrice= 150000},
            {label= 'Neon', vehicleModel = joaat('neon'), vehiclePrice= 200000},
            {label= '9F', vehicleModel = joaat('ninef'), vehiclePrice= 65000},
            {label= '9F Cabrio', vehicleModel = joaat('ninef2'), vehiclePrice= 80000},
            {label= 'Omnis', vehicleModel = joaat('omnis'), vehiclePrice= 35000},
            {label= 'Omnis e-GT', vehicleModel = joaat('omnisegt'), vehiclePrice= 105000},
            {label= 'Panthere', vehicleModel = joaat('panthere'), vehiclePrice= 55000},
            {label= 'Paragon R', vehicleModel = joaat('paragon'), vehiclePrice= 50000},
            {label= 'Pariah', vehicleModel = joaat('pariah'), vehiclePrice= 1420000},
            {label= 'Penumbra', vehicleModel = joaat('penumbra'), vehiclePrice= 28000},
            {label= 'Penumbra FF', vehicleModel = joaat('penumbra2'), vehiclePrice= 37500},
            {label= 'R300', vehicleModel = joaat('r300'), vehiclePrice= 47500},
            {label= 'raiden', vehicleModel = joaat('raiden'), vehiclePrice= 1375000},
            {label= 'Rapid GT', vehicleModel = joaat('rapidgt'), vehiclePrice= 35000},
            {label= 'Rapid GT Cabrio', vehicleModel = joaat('rapidgt2'), vehiclePrice= 45000},
            {label= 'Raptor', vehicleModel = joaat('raptor'), vehiclePrice= 37500},
            {label= 'Remus', vehicleModel = joaat('remus'), vehiclePrice= 28000},
            {label= 'Revolter', vehicleModel = joaat('revolter'), vehiclePrice= 80000},
            {label= 'RT 3000', vehicleModel = joaat('rt3000'), vehiclePrice= 28499},    
            {label= 'Ruston', vehicleModel = joaat('ruston'), vehiclePrice= 75000},    
            {label= 'Schafter V12', vehicleModel = joaat('schafter3'), vehiclePrice= 110000},    
            {label= 'Schafter LWB', vehicleModel = joaat('schafter4'), vehiclePrice= 80000},    
            {label= 'Schlagen GT', vehicleModel = joaat('schlagen'), vehiclePrice= 110000},    
            {label= 'Schwartzer', vehicleModel = joaat('schwarzer'), vehiclePrice= 37500},    
            {label= 'Sentinel3', vehicleModel = joaat('sentinel3'), vehiclePrice= 90000},    
            {label= 'Sentinel Classic Widebody', vehicleModel = joaat('sentinel4'), vehiclePrice= 100000},    
            {label= 'Seven 70', vehicleModel = joaat('seven70'), vehiclePrice= 150000},    
            {label= 'SM722', vehicleModel = joaat('sm722'), vehiclePrice= 500000},    
            {label= 'Specter', vehicleModel = joaat('specter'), vehiclePrice= 75000},    
            {label= 'Specter Custom', vehicleModel = joaat('specter2'), vehiclePrice= 95000},    
            {label= 'Streiter', vehicleModel = joaat('streiter'), vehiclePrice= 75000},    
            {label= 'Sugoi', vehicleModel = joaat('sugoi'), vehiclePrice= 50000},    
            {label= 'Sultan', vehicleModel = joaat('sultan'), vehiclePrice= 15000},    
            {label= 'Sultan Classic', vehicleModel = joaat('sultan2'), vehiclePrice= 15000},    
            {label= 'Sultan 3', vehicleModel = joaat('sultan3'), vehiclePrice= 23000},    
            {label= 'Surano', vehicleModel = joaat('surano'), vehiclePrice= 50000},   
            {label= 'Drift Tampa', vehicleModel = joaat('tampa2'), vehiclePrice= 80000},
            {label= '10F', vehicleModel = joaat('tenf'), vehiclePrice= 160000},
            {label= '10F Widebody', vehicleModel = joaat('tenf2'), vehiclePrice= 170000},
            {label= 'Tropos', vehicleModel = joaat('tropos'), vehiclePrice= 85000},
            {label= 'Vectre', vehicleModel = joaat('vectre'), vehiclePrice= 45000},
            {label= 'Verlierer', vehicleModel = joaat('verlierer2'), vehiclePrice= 70000},
            {label= 'V-STR', vehicleModel = joaat('vstr'), vehiclePrice= 90000},
            {label= 'zr350', vehicleModel = joaat('zr350'), vehiclePrice= 38500},

            
        }},
        {label = 'classics', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Ardent', vehicleModel = joaat('ardent'), vehiclePrice = 50000},
            {label= 'Btype', vehicleModel = joaat('btype'), vehiclePrice= 32000},
            {label= 'Btype Hotroad', vehicleModel = joaat('btype2'), vehiclePrice= 32000},
            {label= 'Btype Luxe', vehicleModel = joaat('btype3'), vehiclePrice= 32000},
            {label= 'Casco', vehicleModel = joaat('casco'), vehiclePrice= 150000},
            {label= 'Cheburek', vehicleModel = joaat('cheburek'), vehiclePrice= 30000},
            {label= 'Cheetah Classic', vehicleModel = joaat('cheetah2'), vehiclePrice= 50000},
            {label= 'Coquette Classic', vehicleModel = joaat('coquette2'), vehiclePrice= 40000},
            {label= 'Dynasty', vehicleModel = joaat('dynasty'), vehiclePrice= 30000},
            {label= 'Fagaloa', vehicleModel = joaat('fagaloa'), vehiclePrice= 30000},
            {label= 'GT 500', vehicleModel = joaat('gt500'), vehiclePrice= 785000},
            {label= 'Infernus Classic', vehicleModel = joaat('infernus2'), vehiclePrice= 50000},
            {label= 'Manana', vehicleModel = joaat('manana'), vehiclePrice= 12800},
            {label= 'Michelli GT', vehicleModel = joaat('michelli'), vehiclePrice= 30000},
            {label= 'Monroe', vehicleModel = joaat('monroe'), vehiclePrice= 55000},
            {label= 'Nebula Turbo', vehicleModel = joaat('nebula'), vehiclePrice= 30000},
            {label= 'Peyote', vehicleModel = joaat('peyote'), vehiclePrice= 30000},
            {label= 'Peyote Custom', vehicleModel = joaat('peyote3'), vehiclePrice= 35000},
            {label= 'Pigalle', vehicleModel = joaat('pigalle'), vehiclePrice= 20000},
            {label= 'Rapid GT Classic', vehicleModel = joaat('rapidgt3'), vehiclePrice= 885000},
            {label= 'Retinue', vehicleModel = joaat('retinue'), vehiclePrice= 615000},
            {label= 'Retinue MK II', vehicleModel = joaat('retinue2'), vehiclePrice= 35000},
            {label= 'Savestra', vehicleModel = joaat('savestra'), vehiclePrice= 990000},    
            {label= 'Stinger', vehicleModel = joaat('stinger'), vehiclePrice= 80000},    
            {label= 'Stinger GT', vehicleModel = joaat('stingergt'), vehiclePrice= 75000},  
            {label= 'Swinger', vehicleModel = joaat('swinger'), vehiclePrice= 50000},
            {label= 'Torero', vehicleModel = joaat('torero'), vehiclePrice= 50000},
            {label= 'Tornado', vehicleModel = joaat('tornado'), vehiclePrice= 35000},
            {label= 'Tornado Convertible', vehicleModel = joaat('tornado2'), vehiclePrice= 35000},
            {label= 'Tornado 3', vehicleModel = joaat('tornado3'), vehiclePrice= 30000},
            {label= 'Tornado Mariachi', vehicleModel = joaat('tornado4'), vehiclePrice= 30000},
            {label= 'Tornado Custom', vehicleModel = joaat('tornado5'), vehiclePrice= 35000},
            {label= 'Tornado Rat Rod', vehicleModel = joaat('tornado6'), vehiclePrice= 35000},
            {label= 'Turismo Classic', vehicleModel = joaat('turismo2'), vehiclePrice= 50000},
            {label= 'Viseris', vehicleModel = joaat('viseris'), vehiclePrice= 875000},
            {label= 'Z190', vehicleModel = joaat('z190'), vehiclePrice= 900000},
            {label= 'Zion Classic', vehicleModel = joaat('zion3'), vehiclePrice= 30000},
            {label= 'Z-Type', vehicleModel = joaat('ztype'), vehiclePrice= 220000},
        }},
        {label = 'supers', defaultIndex = 2, dbData = 'car', values = {
            {label = 'Adder', vehicleModel = joaat('adder'), vehiclePrice = 1100000},
            {label = 'Autarch', vehicleModel = joaat('autarch'), vehiclePrice = 845000},
            {label = 'Banshee 900R', vehicleModel = joaat('banshee2'), vehiclePrice = 120000},
            {label= 'Bullet', vehicleModel = joaat('bullet'), vehiclePrice= 100000},
            {label= 'Cheetah', vehicleModel = joaat('cheetah'), vehiclePrice= 375000},
            {label= 'Cyclone', vehicleModel = joaat('cyclone'), vehiclePrice= 1890000},
            {label= 'Deveste Eight', vehicleModel = joaat('deveste'), vehiclePrice= 375000},
            {label= 'Emerus', vehicleModel = joaat('emerus'), vehiclePrice= 375000},
            {label= 'Entity XXR', vehicleModel = joaat('entity2'), vehiclePrice= 300000},
            {label= 'Overflod Entity MT', vehicleModel = joaat('entity3'), vehiclePrice= 410000},
            {label= 'Entity XF', vehicleModel = joaat('entityxf'), vehiclePrice= 425000},
            {label= 'FMJ', vehicleModel = joaat('fmj'), vehiclePrice= 185000},
            {label= 'Furia', vehicleModel = joaat('furia'), vehiclePrice= 300000},
            {label= 'GP1', vehicleModel = joaat('gp1'), vehiclePrice= 375000},
            {label= 'Granger 3600LX', vehicleModel = joaat('granger2'), vehiclePrice= 180000},
            {label= 'Ignus', vehicleModel = joaat('ignus'), vehiclePrice= 2500000},
            {label= 'Infernus', vehicleModel = joaat('infernus'), vehiclePrice= 180000},
            {label= 'Itali GTB', vehicleModel = joaat('italigtb'), vehiclePrice= 375000},
            {label= 'Itali GTB Custom', vehicleModel = joaat('italigtb2'), vehiclePrice= 375000},
            {label= 'Krieger', vehicleModel = joaat('krieger'), vehiclePrice= 375000},
            {label= 'RE-7B', vehicleModel = joaat('le7b'), vehiclePrice= 325000},
            {label= 'LM87', vehicleModel = joaat('lm87'), vehiclePrice= 1500000},
            {label= 'Nero', vehicleModel = joaat('nero'), vehiclePrice= 300000},
            {label= 'Nero Custom', vehicleModel = joaat('nero2'), vehiclePrice= 300000},
            {label= 'Osiris', vehicleModel = joaat('osiris'), vehiclePrice= 160000},
            {label= 'Penetrator', vehicleModel = joaat('penetrator'), vehiclePrice= 250000},
            {label= 'Pfister', vehicleModel = joaat('pfister811'), vehiclePrice= 85000},
            {label= 'X80 Proto', vehicleModel = joaat('prototipo'), vehiclePrice= 2500000},
            {label= 'Reaper', vehicleModel = joaat('reaper'), vehiclePrice= 150000},
            {label= 'SC 1', vehicleModel = joaat('sc1'), vehiclePrice= 1603000},    
            {label= 'ETR1', vehicleModel = joaat('sheava'), vehiclePrice= 220000},    
            {label= 'Sultan RS', vehicleModel = joaat('sultanrs'), vehiclePrice= 65000}, 
            {label= 'T20', vehicleModel = joaat('t20'), vehiclePrice= 300000},
            {label= 'Taipan', vehicleModel = joaat('taipan'), vehiclePrice= 375000},
            {label= 'Tempesta', vehicleModel = joaat('tempesta'), vehiclePrice= 375000},
            {label= 'Tezeract', vehicleModel = joaat('tezeract'), vehiclePrice= 375000},
            {label= 'Thrax', vehicleModel = joaat('thrax'), vehiclePrice= 375000},
            {label= 'Tigon', vehicleModel = joaat('tigon'), vehiclePrice= 375000},
            {label= 'Torero XO', vehicleModel = joaat('torero2'), vehiclePrice= 2200000},
            {label= 'Turismo R', vehicleModel = joaat('turismor'), vehiclePrice= 350000},
            {label= 'Tyrant', vehicleModel = joaat('tyrant'), vehiclePrice= 300000},
            {label= 'Tyrus', vehicleModel = joaat('tyrus'), vehiclePrice= 600000},
            {label= 'Vacca', vehicleModel = joaat('vacca'), vehiclePrice= 12000},
            {label= 'Vagner', vehicleModel = joaat('vagner'), vehiclePrice= 375000},
            {label= 'Virtue', vehicleModel = joaat('virtue'), vehiclePrice= 2000000},
            {label= 'Visione', vehicleModel = joaat('visione'), vehiclePrice= 2250000},
            {label= 'Voltic', vehicleModel = joaat('voltic'), vehiclePrice= 90000},
            {label= 'XA-21', vehicleModel = joaat('xa21'), vehiclePrice= 375000},
            {label= 'Zeno', vehicleModel = joaat('zeno'), vehiclePrice= 3000000},
            {label= 'Zentorno', vehicleModel = joaat('zentorno'), vehiclePrice= 1500000},
            {label= 'Zorrusso', vehicleModel = joaat('zorrusso'), vehiclePrice= 375000},
        }},
        {label = 'vans', defaultIndex = 2, dbData = 'car', values = {
            {label= 'Bison', vehicleModel = joaat('bison'), vehiclePrice= 40000},
            {label= 'Bison 3', vehicleModel = joaat('bison3'), vehiclePrice= 40000},
            {label= 'Bobcat XL', vehicleModel = joaat('bobcatxl'), vehiclePrice= 15000},
            {label= 'Burrito Jobs', vehicleModel = joaat('burrito'), vehiclePrice= 20000},
            {label= 'Burrito Bugstars', vehicleModel = joaat('burrito2'), vehiclePrice= 20000},
            {label= 'Burrito', vehicleModel = joaat('burrito3'), vehiclePrice= 20000},
            {label= 'Camper', vehicleModel = joaat('camper'), vehiclePrice= 20000},
            {label= 'Gang Burrito', vehicleModel = joaat('gburrito'), vehiclePrice= 45000},
            {label= 'Burrito', vehicleModel = joaat('gburrito2'), vehiclePrice= 29000},
            {label= 'Journey', vehicleModel = joaat('journey'), vehiclePrice= 6500},
            {label= 'Journey II', vehicleModel = joaat('journey2'), vehiclePrice= 6500},
            {label= 'Minivan', vehicleModel = joaat('minivan'), vehiclePrice= 13000},
            {label= 'Minivan Custom', vehicleModel = joaat('minivan2'), vehiclePrice= 20000},
            {label= 'Moonbeam', vehicleModel = joaat('moonbeam'), vehiclePrice= 18000},
            {label= 'Moonbeam Rider', vehicleModel = joaat('moonbeam2'), vehiclePrice= 35000},
            {label= 'Paradise', vehicleModel = joaat('paradise'), vehiclePrice= 19000},
            {label= 'Pony', vehicleModel = joaat('pony'), vehiclePrice= 25000},
            {label= 'Pony 2', vehicleModel = joaat('pony2'), vehiclePrice= 25000},
            {label= 'Rumpo', vehicleModel = joaat('rumpo'), vehiclePrice= 15000},    
            {label= 'Rumpo Trail', vehicleModel = joaat('rumpo3'), vehiclePrice= 19500},  
            {label= 'Slam Truck', vehicleModel = joaat('slamtruck'), vehiclePrice= 15000},    
            {label= 'Speedo', vehicleModel = joaat('speedo'), vehiclePrice= 20000},    
            {label= 'Surfer', vehicleModel = joaat('surfer'), vehiclePrice= 12000},    
            {label= 'BF Surfer', vehicleModel = joaat('surfer2'), vehiclePrice= 10000},    
            {label= 'BF Surfer Custom', vehicleModel = joaat('surfer3'), vehiclePrice= 15000},   
            {label= 'Youga', vehicleModel = joaat('youga'), vehiclePrice= 10800},
            {label= 'Youga Luxuary', vehicleModel = joaat('youga2'), vehiclePrice= 14500},
            {label= 'Youga Classic 4x4', vehicleModel = joaat('youga3'), vehiclePrice= 25000},
            {label= 'Youga Custom', vehicleModel = joaat('youga4'), vehiclePrice= 450000},
        }},
        -- {label = 'truck', defaultIndex = 2, dbData = 'car', values = {
        --     {label = 'Benson', vehicleModel = joaat('benson'), vehiclePrice = 18200},
        --     {label = 'Benson job', vehicleModel = joaat('benson2'), vehiclePrice = 18000},
        --     {label= 'Hauler', vehicleModel = joaat('hauler'), vehiclePrice= 45000},
        --     {label= 'Mule', vehicleModel = joaat('mule'), vehiclePrice= 45000},
        --     {label= 'Mule 2', vehicleModel = joaat('mule2'), vehiclePrice= 45000},
        --     {label= 'Mule 3', vehicleModel = joaat('mule3'), vehiclePrice= 45000},
        --     {label= 'Mule custom', vehicleModel = joaat('mule4'), vehiclePrice= 45000},
        --     {label= 'Mule 5', vehicleModel = joaat('mule5'), vehiclePrice= 45000},
        --     {label= 'Packer', vehicleModel = joaat('packer'), vehiclePrice= 69500},
        --     {label= 'Phantom', vehicleModel = joaat('phantom'), vehiclePrice= 61500},
        --     {label= 'Phantom Custom', vehicleModel = joaat('phantom3'), vehiclePrice= 61500},
        --     {label= 'Pounder Custom', vehicleModel = joaat('pounder2'), vehiclePrice= 200000},
        --     {label= 'Rally Truck', vehicleModel = joaat('rallytruck'), vehiclePrice= 220000},
        -- }},
        {label = 'others', defaultIndex = 2, dbData = 'car', values = {
            {label= 'Patriot Stretch', vehicleModel = joaat('patriot2'), vehiclePrice= 150000},
            {label= 'Stretch', vehicleModel = joaat('stretch'), vehiclePrice= 90000},
        }},
        
    },
    ['boats'] = {
        {label = 'Jetski', defaultIndex = 2, dbData = 'boat', values = {
            {label = 'Seashark', vehicleModel = joaat('seashark'), vehiclePrice = 1000}, 
            {label = 'Seashark', vehicleModel = joaat('seashark2'), vehiclePrice = 1000}, 
            {label = 'Seashark', vehicleModel = joaat('seashark3'), vehiclePrice = 1000},
        }},
        {label = 'Bateaux', defaultIndex = 2, dbData = 'boat', values = {
            {label = 'Dinghy', vehicleModel = joaat('dinghy'), vehiclePrice = 1000}, 
            {label = 'DinghyB', vehicleModel = joaat('dinghy2'), vehiclePrice = 1000}, 
            {label = 'DinghyC', vehicleModel = joaat('dinghy3'), vehiclePrice = 1000},
            {label = 'DinghyD', vehicleModel = joaat('dinghy4'), vehiclePrice = 1000}, 
        }},
        {label = 'Bateaux de croisière', defaultIndex = 2, dbData = 'boat', values = {
            {label = 'Jetmax', vehicleModel = joaat('jetmax'), vehiclePrice = 1000}, 
            {label = 'Speeder', vehicleModel = joaat('speeder'), vehiclePrice = 1000}, 
            {label = 'SpeederB', vehicleModel = joaat('speeder2'), vehiclePrice = 1000},
            {label = 'Squalo', vehicleModel = joaat('squalo'), vehiclePrice = 1000},
            {label = 'Suntrap', vehicleModel = joaat('suntrap'), vehiclePrice = 1000},
            {label = 'Toro', vehicleModel = joaat('toro'), vehiclePrice = 1000},
            {label = 'ToroB', vehicleModel = joaat('toro2'), vehiclePrice = 1000},
            {label = 'Tropic', vehicleModel = joaat('tropic'), vehiclePrice = 1000},
            {label = 'TropicB', vehicleModel = joaat('tropic2'), vehiclePrice = 1000},
            {label = 'Longfin', vehicleModel = joaat('longfin'), vehiclePrice = 1000},
       }},
    },
    ['planes'] = {
        {label = 'Helicoptère', defaultIndex = 2, dbData = 'plane', values = {
            {label = 'havok', vehicleModel = joaat('havok'), vehiclePrice = 1000}, 
            {label = 'nokota', vehicleModel = joaat('nokota'), vehiclePrice = 1000}, 
        }},
    },

}